openapi: 3.0.3
info:
  title: Payment Instrument API documentation
  description: |
    Payment Instrument and Cardholder operation management include APIs for Payment Instrument maintenance, Payment instrument operations, and Status operation.
  version: PowerCARD-Issuer 3.5.4-apiR5.3
servers:
- url: ${sandbox.backend.connectApiUrl}/rest
  description: Development server
security:
- bearerAuth: [
    ]
paths:
  /AddMerchantBankAccount/V3:
    post:
      tags:
      - Add Merchant Bank Account
      summary: addMerchantBankAccount_35
      description: 'addMerchantBankAccount_35 Web Service '
      operationId: addMerchantBankAccount_35Post_2
      requestBody:
        description: AddMerchantBankAccountV353Rq Request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddMerchantBankAccountV353Rq'
        required: true
      responses:
        '200':
          description: ProceedWithSuccess
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddMerchantBankAccountV353Rs'
      servers:
      - url: /PowerCardConnectApi/rest
        variables: {
          }
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        <div>
          <h5>Api key authorization</h5>
          <p>JWT authorization header using Bearer scheme. Example: "Authorization: Bearer {token}"</p>
          <table>
            <tr><td>Name:</td><td>Authorization</td></tr>
            <tr><td>In:</td><td>Header</td></tr>
          </table>
        </div>
  schemas:
    AddMerchantBankAccountV353Rq:
      required:
      - requestInfo
      type: object
      properties:
        requestInfo:
          $ref: '#/components/schemas/RequestInfo'
        merchantIdInfo:
          $ref: '#/components/schemas/MerchantIdInfoV35'
        merchantAccount:
          $ref: '#/components/schemas/MerchantAccountV35'
    AddMerchantBankAccountV353Rs:
      required:
      - responseInfo
      type: object
      properties:
        responseInfo:
          $ref: '#/components/schemas/ResponseInfo'
        accountSeqID:
          maxLength: 15
          minLength: 0
          pattern: ^[A-Za-z0-9]*$
          type: string
          xml:
            name: AccountSeqID
    ResponseInfo:
      required:
      - errorCode
      - errorDescription
      - responseUID
      - resultID
      type: object
      properties:
        responseUID:
          type: string
          xml:
            name: ResponseUID
        resultID:
          type: string
          xml:
            name: ResultID
          enum:
          - ProceedWithSuccess
          - ProceedWithSuccessMC
          - Error
          - SystemError
        errorCode:
          type: string
          xml:
            name: ErrorCode
        errorDescription:
          type: string
          xml:
            name: ErrorDescription
    KeyValueV35:
      required:
      - data
      - key
      type: object
      properties:
        key:
          maxLength: 30
          minLength: 0
          pattern: ^[a-zA-Z0-9-#$_@&*.%+\s\/]*$
          type: string
          xml:
            name: Key
        data:
          maxLength: 64
          minLength: 0
          pattern: ^[a-zA-Z0-9-#$_@&*.%+\s\/]*$
          type: string
          xml:
            name: Data
        type:
          pattern: ^[A-Za-z0-9]*$
          type: string
          xml:
            name: Type
    MerchantAccountV35:
      required:
      - accountBankCode
      - accountBranchCode
      - accountCategory
      - accountCurrency
      - accountNumber
      - accountType
      - batchGrouping
      - billableElementGrouping
      - chargebackGrouping
      - feesGrouping
      type: object
      properties:
        accountSeqID:
          maxLength: 2
          minLength: 0
          pattern: ^[A-Za-z0-9]*$
          type: string
          xml:
            name: AccountSeqID
        entityId:
          maxLength: 24
          minLength: 0
          pattern: ^[A-Za-z0-9]*$
          type: string
          xml:
            name: EntityId
        accountType:
          maxLength: 1
          minLength: 0
          pattern: ^[A-Za-z0-9]*$
          type: string
          xml:
            name: AccountType
        chainBankCode:
          maxLength: 6
          minLength: 0
          pattern: ^[A-Za-z0-9]*$
          type: string
          xml:
            name: ChainBankCode
        chainCode:
          maxLength: 15
          minLength: 0
          pattern: ^[A-Za-z0-9]*$
          type: string
          xml:
            name: ChainCode
        accountCategory:
          maxLength: 2
          minLength: 0
          pattern: ^[A-Za-z0-9]*$
          type: string
          xml:
            name: AccountCategory
        accountBankCode:
          maxLength: 6
          minLength: 0
          pattern: ^[A-Za-z0-9]*$
          type: string
          xml:
            name: AccountBankCode
        accountBranchCode:
          maxLength: 6
          minLength: 0
          pattern: ^[A-Za-z0-9]*$
          type: string
          xml:
            name: AccountBranchCode
        accountNumber:
          maxLength: 24
          minLength: 0
          pattern: ^[A-Za-z0-9]*$
          type: string
          xml:
            name: AccountNumber
        accountCurrency:
          maxLength: 3
          minLength: 0
          pattern: ^[A-Za-z0-9]*$
          type: string
          xml:
            name: AccountCurrency
        bic:
          maxLength: 40
          minLength: 0
          type: string
          xml:
            name: Bic
        iban:
          maxLength: 34
          minLength: 0
          type: string
          xml:
            name: Iban
        coreSystemReference:
          maxLength: 64
          minLength: 0
          pattern: ^[a-zA-Z0-9-#$_@&*.%+\s\/]*$
          type: string
          xml:
            name: CoreSystemReference
        accountStatus:
          maxLength: 1
          minLength: 0
          pattern: ^[A-Za-z0-9]*$
          type: string
          xml:
            name: AccountStatus
        batchGrouping:
          maxLength: 1
          minLength: 0
          pattern: ^[A-Za-z0-9]*$
          type: string
          xml:
            name: BatchGrouping
        feesGrouping:
          maxLength: 1
          minLength: 0
          pattern: ^[A-Za-z0-9]*$
          type: string
          xml:
            name: FeesGrouping
        billableElementGrouping:
          maxLength: 1
          minLength: 0
          pattern: ^[A-Za-z0-9]*$
          type: string
          xml:
            name: BillableElementGrouping
        chargebackGrouping:
          maxLength: 1
          minLength: 0
          pattern: ^[A-Za-z0-9]*$
          type: string
          xml:
            name: ChargebackGrouping
        routingNumber:
          maxLength: 9
          minLength: 0
          pattern: ^[A-Za-z0-9]*$
          type: string
          xml:
            name: RoutingNumber
    RequestInfo:
      required:
      - requestDate
      - requestUID
      type: object
      properties:
        requestUID:
          pattern: ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$
          type: string
          xml:
            name: RequestUID
        userID:
          maxLength: 15
          minLength: 0
          pattern: ^[a-zA-Z0-9-#$_@&*.%+\s\/]*$
          type: string
          xml:
            name: UserID
        requestDate:
          type: string
          format: date-time
          xml:
            name: RequestDate
    MerchantIdInfoV35:
      required:
      - bankCode
      type: object
      properties:
        bankCode:
          maxLength: 6
          minLength: 0
          pattern: ^[A-Za-z0-9]*$
          type: string
          xml:
            name: BankCode
        merchantID:
          maxLength: 15
          minLength: 0
          pattern: ^[A-Za-z0-9]*$
          type: string
          xml:
            name: MerchantID
        legalID:
          maxLength: 15
          minLength: 0
          pattern: ^[A-Za-z0-9]*$
          type: string
          xml:
            name: LegalID
