openapi: 3.0.3
info:
  title: Payment Instrument API documentation
  description: |
    Payment Instrument and Cardholder operation management include APIs for Payment Instrument maintenance, Payment instrument operations, and Status operation.
  version: PowerCARD-Issuer 3.5.4-apiR5.3
servers:
- url: ${sandbox.backend.connectApiUrl}/rest
  description: Development server
security:
- bearerAuth: [
    ]
paths:
  /ApplePayEncryption/V3:
    post:
      tags:
      - Apple Pay Encryption
      summary: 'Apple Pay  Encryption '
      description: Apple Pay  Encryption Web WebService
      operationId: applepayencryption_35Post_1
      requestBody:
        description: ApplePayEncryption Request
        content:
          application/json:
            schema:
              $ref: ./request.yaml#/ApplePayEncryption2V35Rq
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./response.yaml#/ApplePayEncryption2V35Rs
          description: Default response for 200
      servers:
      - url: /PowerCardConnectApi/rest
        variables: {
          }
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        <div>
          <h5>Api key authorization</h5>
          <p>JWT authorization header using Bearer scheme. Example: "Authorization: Bearer {token}"</p>
          <table>
            <tr><td>Name:</td><td>Authorization</td></tr>
            <tr><td>In:</td><td>Header</td></tr>
          </table>
        </div>
  schemas:
    ApplePayEncryption2V35Rq:
      $ref: ./request.yaml#/ApplePayEncryption2V35Rq
    ApplePayEncryption2V35Rs:
      $ref: ./response.yaml#/ApplePayEncryption2V35Rs
