openapi: 3.0.3
info:
  title: Payment Instrument API documentation
  description: |
    Payment Instrument and Cardholder operation management include APIs for Payment Instrument maintenance, Payment instrument operations, and Status operation.
  version: PowerCARD-Issuer 3.5.4-apiR5.3
servers:
- url: ${sandbox.backend.connectApiUrl}/rest
  description: Development server
security:
- bearerAuth: [
    ]
paths:
  /AddMerchantBankAccount/V3:
    post:
      tags:
      - Add Merchant Bank Account
      summary: addMerchantBankAccount_35
      description: 'addMerchantBankAccount_35 Web Service '
      operationId: addMerchantBankAccount_35Post_2
      requestBody:
        description: AddMerchantBankAccountV353Rq Request
        content:
          application/json:
            schema:
              $ref: ./request.yaml#/AddMerchantBankAccountV353Rq
        required: true
      responses:
        '200':
          description: ProceedWithSuccess
          content:
            application/json:
              schema:
                $ref: ./response.yaml#/AddMerchantBankAccountV353Rs
      servers:
      - url: /PowerCardConnectApi/rest
        variables: {
          }
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        <div>
          <h5>Api key authorization</h5>
          <p>JWT authorization header using Bearer scheme. Example: "Authorization: Bearer {token}"</p>
          <table>
            <tr><td>Name:</td><td>Authorization</td></tr>
            <tr><td>In:</td><td>Header</td></tr>
          </table>
        </div>
  schemas:
    AddMerchantBankAccountV353Rq:
      $ref: ./request.yaml#/AddMerchantBankAccountV353Rq
    AddMerchantBankAccountV353Rs:
      $ref: ./response.yaml#/AddMerchantBankAccountV353Rs
